/**
 * Identification string.
 *
 * Return the string representation of a garment identification.
 *
 * @author Etienne Bolduc
 */

import { identify, extract, CDG, IM, MM, YY } from "./index.js";

const CDG_YEAR_BLANK = CDG.NoYearPrint.BLANK;
const CDG_YEAR_UNREADABLE = CDG.NoYearPrint.UNREADABLE;
const CDG_YEAR_UNSPECIFIED = CDG.NoYearPrint.UNSPECIFIED;

const inputCDG = [
    { label: CDG.Label, productCode: "S18B001", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "CDGS2ST", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "FO01B601", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "S11001", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "W23001", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "FW-01001", yearPrint: "1994" },
    { label: CDG.Label, productCode: "HB-08000M", yearPrint: CDG_YEAR_UNSPECIFIED },
    { label: CDG.Label, productCode: "PB-11001M", yearPrint: "1994" },
    { label: CDG.Label, productCode: "PP-C002", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "EP-C002", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "AB-35003", yearPrint: CDG_YEAR_UNSPECIFIED },
    { label: CDG.Label, productCode: "KK-27003", yearPrint: CDG_YEAR_UNSPECIFIED },
    { label: CDG.Label, productCode: "KK-K004", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "7D-K004", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "OC-K004", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "AZT026", yearPrint: "2005" },
    { label: CDG.Label, productCode: "AZT026", yearPrint: "2006" },
    { label: CDG.Label, productCode: "DTK9210", yearPrint: "2006" },
    { label: CDG.Label, productCode: "EP-C002", yearPrint: "1986" },
    { label: CDG.Label, productCode: "FW09123", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "FW09123", yearPrint: "2001" },
    { label: CDG.Label, productCode: "HB-08123M", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "HB-08123M", yearPrint: CDG_YEAR_UNSPECIFIED },
    { label: CDG.Label, productCode: "PB-02123M", yearPrint: CDG_YEAR_UNREADABLE },
    { label: CDG.Label, productCode: "HB-02123M", yearPrint: CDG_YEAR_UNREADABLE },
    { label: CDG.Label, productCode: "PB-05123M", yearPrint: CDG_YEAR_UNREADABLE },
    { label: CDG.Label, productCode: "HB-05123M", yearPrint: CDG_YEAR_UNREADABLE },
    { label: CDG.Label, productCode: "PB-08123M", yearPrint: CDG_YEAR_UNREADABLE },
    { label: CDG.Label, productCode: "HB-08123M", yearPrint: CDG_YEAR_UNREADABLE },
    { label: CDG.Label, productCode: "PB-11123M", yearPrint: CDG_YEAR_UNREADABLE },
    { label: CDG.Label, productCode: "HB-11123M", yearPrint: CDG_YEAR_UNREADABLE },
    { label: CDG.Label, productCode: "OP-K402", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "GU-05004S", yearPrint: "1989" },
    { label: CDG.Label, productCode: "1P-P002", yearPrint: "2005" },
    { label: CDG.Label, productCode: "", yearPrint: "" },
    { label: CDG.Label, productCode: "DTK9210", yearPrint: "2006" },
    { label: CDG.Label, productCode: "GB-N004", yearPrint: "2008" },
    { label: CDG.Label, productCode: "AZT026", yearPrint: "2005" },
    { label: CDG.Label, productCode: "SE-T902", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "XB-08000M", yearPrint: "1994" },
    { label: CDG.Label, productCode: "PB-B018", yearPrint: "2017" },
    { label: CDG.Label, productCode: "S9OP15", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "GB-J024", yearPrint: "2017" },
    { label: CDG.Label, productCode: "W11SC03", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "OO-K001", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "AZT026", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "AZB001", yearPrint: "AD2016/12" },
    { label: CDG.Label, productCode: "WI-C001", yearPrint: CDG_YEAR_BLANK },
    { label: CDG.Label, productCode: "DR-2005-01", yearPrint: "2004" },
    { label: CDG.Label, productCode: "PB-11123M", yearPrint: CDG_YEAR_UNREADABLE },
];

const YY_CODE_BLANK = YY.NoProductCode.BLANK;
const YY_CODE_UNREADABLE = YY.NoProductCode.UNREADABLE;
const YY_CODE_UNSPECIFIED = YY.NoProductCode.UNSPECIFIED;

const YY_LOGO_YY_1 = YY.LogoStyle.YOHJI_YAMAMOTO.ROUND;
const YY_LOGO_YY_2 = YY.LogoStyle.YOHJI_YAMAMOTO.ROUGH;
const YY_LOGO_YY_3 = YY.LogoStyle.YOHJI_YAMAMOTO.SKEWED;
const YY_LOGO_YY_4 = YY.LogoStyle.YOHJI_YAMAMOTO.EVEN;
const YY_LOGO_YS_1 = YY.LogoStyle.YS.ANY.SANS_SERIF;
const YY_LOGO_YS_2 = YY.LogoStyle.YS.ANY.SERIF;
const YY_LOGO_YS_B = YY.LogoStyle.YS.BRUSH;
const YY_LOGO_NOIR_1 = YY.LogoStyle.NOIR_SANS_SERIF;
const YY_LOGO_UNSPECIFIED = YY.LogoStyle.UNSPECIFIED;

const YY_SIZING_ALPHABETICAL = YY.Sizing.ALPHABETICAL;
const YY_SIZING_NUMERICAL = YY.Sizing.NUMERICAL;
const YY_SIZING_UNSPECIFIED = YY.Sizing.UNSPECIFIED;

const YY_TYPEFACE_PROP = YY.Typeface.PROPORTIONAL;
const YY_TYPEFACE_MONO = YY.Typeface.MONOSPACED;
const YY_TYPEFACE_SLAB = YY.Typeface.SLAB_SERIF;
const YY_TYPEFACE_UNSPECIFIED = YY.Typeface.UNSPECIFIED;

const YY_LANGUAGE_JP = YY.Language.JP;
const YY_LANGUAGE_FR_EN_JP = YY.Language.FR_EN_JP;
const YY_LANGUAGE_UNSPECIFIED = YY.Language.UNSPECIFIED;

const YY_LAUNDRY_TOP = YY.LaundryPosition.TOP;
const YY_LAUNDRY_BOTTOM = YY.LaundryPosition.BOTTOM;
const YY_LAUNDRY_UNSPECIFIED = YY.LaundryPosition.UNSPECIFIED;

const YY_TUMBLE_UNSPECIFIED = YY.DoNotTumbleDry.UNSPECIFIED;
const YY_TUMBLE_BLANK = YY.DoNotTumbleDry.BLANK;
const YY_TUMBLE_LONG = YY.DoNotTumbleDry.LONG;
const YY_TUMBLE_SHORT = YY.DoNotTumbleDry.SHORT;

const YY_MANUFACTURER_BLANK = YY.Manufacturer.BLANK;
const YY_MANUFACTURER_YS_CO_LTD = YY.Manufacturer.YS_CO_LTD;
//const YY_MANUFACTURER_YS_BIS_CO_LTD = YY.Manufacturer.YSBIS;
const YY_MANUFACTURER_YOHJI_YAMAMOTO_INC = YY.Manufacturer.YOHJI_YAMAMOTO_INC;
const YY_MANUFACTURER_UNSPECIFIED = YY.Manufacturer.UNSPECIFIED;

const inputYY = [
    { label: YY.Label, productCode: "HZ-B10-104", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_BLANK, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_BLANK, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "FY-C10-104", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "FY-C10-104", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "FY-C10-104", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HO-K27-037", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HG-C21-035", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HN-Y01-003", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "FD-J17-135", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "FD-J17-135", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNREADABLE, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HV-C00-000", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HW-Y11-701", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HJ-C37-146-1-01", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_2,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_2,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_2,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HB-T00-000", logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "SJ-T00-000", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_BLANK, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_BLANK, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HB-T00-000", logoStyle: YY_LOGO_YY_1,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HW-Y11-701", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HB-T00-000", logoStyle: YY_LOGO_YY_2,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HV-B00-000", logoStyle: YY_LOGO_YY_2,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HV-B00-000", logoStyle: "wrong",
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HE-B00-000", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "FE-H02-180-1M", logoStyle: YY_LOGO_YY_2,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "FE-H02-180-111", logoStyle: YY_LOGO_YY_2,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HF-B06-933", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HF-B06-933", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HE-B23-288", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "K-T11-045", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_BLANK, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_PROP,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_TOP,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_BLANK, logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNREADABLE, logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_UNSPECIFIED, logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_BLANK, logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_BLANK, logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "MB-B10-100", logoStyle: YY_LOGO_YS_2,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "YA-T65-052", logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HA-T65-052", logoStyle: YY_LOGO_YY_3,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "YQ-T65-052", logoStyle: YY_LOGO_YS_2,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "FY-P55-100", logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "NG-B00-000", logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "UP-B00-000", logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HP-A81-775-1-03", logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "MP-Y00-000", logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "YV-B00-000", logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED,  laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "NB-B00-000", logoStyle: YY_LOGO_NOIR_1,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED,  laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HT-B81-775", logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_BLANK, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HT-B81-775", logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_LONG, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "HT-B81-775", logoStyle: YY_LOGO_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_SHORT, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: YY_CODE_BLANK, logoStyle: YY_LOGO_YY_2,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_SHORT, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "YU-D09-045", logoStyle: YY_LOGO_YS_2,
                    sizing: YY_SIZING_NUMERICAL, typeface: YY_TYPEFACE_MONO,
                    language: YY_LANGUAGE_FR_EN_JP, laundryPosition: YY_LAUNDRY_BOTTOM,
                    doNotTumbleDry: YY_TUMBLE_LONG, manufacturer: YY_MANUFACTURER_YOHJI_YAMAMOTO_INC },
    { label: YY.Label, productCode: "YU-D09-045", logoStyle: YY_TYPEFACE_UNSPECIFIED,
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "YU-D09-045", logoStyle: "YS_ANY_SERIF",
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "YU-D09-045", logoStyle: "YS_YOHJI_YAMAMOTO_ABSENT",
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "YU-D09-045", logoStyle: "YS_YOHJI_YAMAMOTO_RIGHT",
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "YU-D09-045", logoStyle: "YS_FOR_MEN_SANS_SERIF",
                    sizing: YY_SIZING_UNSPECIFIED, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: YY_TUMBLE_UNSPECIFIED, manufacturer: YY_MANUFACTURER_UNSPECIFIED },
    { label: YY.Label, productCode: "MO-D09-045", logoStyle: "YS_FOR_MEN_YOHJI_YAMAMOTO_UNDER",
                    sizing: YY_SIZING_ALPHABETICAL, typeface: YY_TYPEFACE_UNSPECIFIED,
                    language: YY_LANGUAGE_UNSPECIFIED, laundryPosition: YY_LAUNDRY_UNSPECIFIED,
                    doNotTumbleDry: "HIRAGANA", manufacturer: YY_MANUFACTURER_UNSPECIFIED },
];

const IM_LOGO_ROUND = IM.LogoStyle.ROUND;
const IM_LOGO_BRUSH = IM.LogoStyle.BRUSH;
const IM_LOGO_IM_BLACK_ON_WHITE = IM.LogoStyle.IM.BLACK_ON_WHITE;
const IM_LOGO_IM_WHITE_ON_BLACK = IM.LogoStyle.IM.WHITE_ON_BLACK;
const IM_LOGO_ME_BLACK_ON_WHITE = IM.LogoStyle.ME.BLACK_ON_WHITE;
const IM_LOGO_ME_WHITE_ON_BLACK = IM.LogoStyle.ME.WHITE_ON_BLACK;
const IM_LOGO_UNSPECIFIED = IM.LogoStyle.UNSPECIFIED;

const IM_MANUFACTURER_IM_INC = IM.Manufacturer.IM_INC;
const IM_MANUFACTURER_IM_INTL_INC = IM.Manufacturer.IM_INTL_INC;
const IM_MANUFACTURER_ON_LIMITS = IM.Manufacturer.ON_LIMITS;
const IM_MANUFACTURER_ANET = IM.Manufacturer.ANET;
const IM_MANUFACTURER_UNSPECIFIED = IM.Manufacturer.UNSPECIFIED;

const IM_SIZING_ALPHABETICAL = IM.Sizing.ALPHABETICAL;
const IM_SIZING_NUMERICAL = IM.Sizing.NUMERICAL;
const IM_SIZING_UNSPECIFIED = IM.Sizing.UNSPECIFIED;

const IM_TYPEFACE_SLAB_SERIF = IM.Typeface.SLAB_SERIF;
const IM_TYPEFACE_SANS_SERIF = IM.Typeface.SANS_SERIF;
const IM_TYPEFACE_UNSPECIFIED = IM.Typeface.UNSPECIFIED;

const inputIM = [
    { label: IM.Label, productCode: "ME13FA026", logoStyle: IM_LOGO_IM_WHITE_ON_BLACK,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "ME81JK648", logoStyle: IM_LOGO_ME_BLACK_ON_WHITE,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "ME03JK471", logoStyle: IM_LOGO_ME_BLACK_ON_WHITE,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "ME46-FF095", logoStyle: IM_LOGO_IM_WHITE_ON_BLACK,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "IM71-FF027", logoStyle: IM_LOGO_IM_BLACK_ON_WHITE,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "IM54-FD509", logoStyle: IM_LOGO_IM_BLACK_ON_WHITE,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "ME11FD021", logoStyle: IM_LOGO_ME_WHITE_ON_BLACK,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "ME78-JK180", logoStyle: IM_LOGO_ME_WHITE_ON_BLACK,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "PP64-JH732", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "IM13JK077", logoStyle: IM_LOGO_IM_WHITE_ON_BLACK,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "JY14230", logoStyle: IM_LOGO_IM_BLACK_ON_WHITE,
        manufacturer: IM_MANUFACTURER_IM_INTL_INC, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "RY81446", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_IM_INTL_INC, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "LH14759", logoStyle: IM_LOGO_ROUND,
        manufacturer: IM_MANUFACTURER_IM_INTL_INC, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "LH14759", logoStyle: IM_LOGO_ROUND,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "ME81JK648", logoStyle: IM_LOGO_ME_BLACK_ON_WHITE,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "BY84446", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "0CL24002", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "OCL24002", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "0AJ14007", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "9AL31053", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "XM38511DD", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "KL37801", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "XZ17261AC", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "MP63220", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_ON_LIMITS, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "FK53344", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_ON_LIMITS, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "MY32108", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_ON_LIMITS, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "LG23088", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_ON_LIMITS, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "LG63088", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_ON_LIMITS, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "LG63088", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_ON_LIMITS, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "MB04116", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "IM54-FD509", logoStyle: IM_LOGO_IM_BLACK_ON_WHITE,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "LH14759", logoStyle: IM_LOGO_ROUND,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "PP05JK004", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "PP87JK004", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "IS21FD012", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "IS13FD012", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "FH01FD012", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "FH55FD012", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "PP55-FD012/4", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "IM04-FD012", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "CF007KG020", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "AT55KF420/1", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "GG13AG151-19", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "PP24AG151", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "TM63AG151", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "ME34AD151", logoStyle: IM_LOGO_IM_WHITE_ON_BLACK,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "ME62FF102", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "ZU47FF102", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "IM13FF102", logoStyle: IM_LOGO_IM_WHITE_ON_BLACK,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "CZ94FF102", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "CZ94FF102", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "TC94FF102", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "LG51419", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_IM_INTL_INC, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "GG13079", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_IM_INTL_INC, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "ME01FJ000", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "ME63FJ000", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "CL43FJ000", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "CL43FJ000", logoStyle: IM_LOGO_IM_WHITE_ON_BLACK,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "CL63FJ000", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
        typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "ME63FJ000", logoStyle: IM_LOGO_UNSPECIFIED,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_NUMERICAL,
        typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "EG36395", logoStyle: IM_LOGO_BRUSH,
        manufacturer: IM_MANUFACTURER_ON_LIMITS, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "ZC36103", logoStyle: IM_LOGO_ROUND,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "0GH11025", logoStyle: IM_LOGO_IM_WHITE_ON_BLACK,
        manufacturer: IM_MANUFACTURER_ON_LIMITS, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "ME63-FC460", logoStyle: IM_LOGO_ME_BLACK_ON_WHITE,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "JY11097", logoStyle: IM_LOGO_BRUSH,
        manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "PL04-FA713", logoStyle: null,
            manufacturer: IM_MANUFACTURER_ANET, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "PP06-JF595", logoStyle: null,
            manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "IM19-JO556", logoStyle: IM_LOGO_IM_BLACK_ON_WHITE,
            manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SLAB_SERIF },
    { label: IM.Label, productCode: "PP56-JT994", logoStyle: IM_LOGO_IM_BLACK_ON_WHITE,
            manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "IF34-FD102", logoStyle: IM_LOGO_UNSPECIFIED,
            manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_NUMERICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "SS61211", logoStyle: IM_LOGO_BRUSH,
            manufacturer: IM_MANUFACTURER_ON_LIMITS, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "EG36395", logoStyle: IM_LOGO_BRUSH,
            manufacturer: IM_MANUFACTURER_ON_LIMITS, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "EG36395", logoStyle: IM_LOGO_BRUSH,
            manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "0DL45536", logoStyle: IM_LOGO_IM_WHITE_ON_BLACK,
            manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "0BL45536", logoStyle: IM_LOGO_IM_WHITE_ON_BLACK,
            manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "9DL45536", logoStyle: IM_LOGO_IM_WHITE_ON_BLACK,
            manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "0DL45536", logoStyle: IM_LOGO_IM_WHITE_ON_BLACK,
            manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "LG51419", logoStyle: IM_LOGO_IM_BLACK_ON_WHITE,
            manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "EG53410", logoStyle: IM_LOGO_IM_BLACK_ON_WHITE,
            manufacturer: IM_MANUFACTURER_IM_INC, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "EG53410", logoStyle: IM_LOGO_IM_BLACK_ON_WHITE,
            manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "EG53410", logoStyle: IM_LOGO_UNSPECIFIED,
            manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "RG34140", logoStyle: IM_LOGO_UNSPECIFIED,
            manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_ALPHABETICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
    { label: IM.Label, productCode: "IM09-FS001", logoStyle: IM_LOGO_UNSPECIFIED,
            manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_UNSPECIFIED,
            typeface: IM_TYPEFACE_UNSPECIFIED },
    { label: IM.Label, productCode: "IM88-FT008", logoStyle: IM_LOGO_IM_BLACK_ON_WHITE,
            manufacturer: IM_MANUFACTURER_UNSPECIFIED, sizing: IM_SIZING_NUMERICAL,
            typeface: IM_TYPEFACE_SANS_SERIF },
];

const MM_CODE_BLANK = MM.NoProductCode.BLANK;
const MM_CODE_UNREADABLE = MM.NoProductCode.UNREADABLE;
const MM_CODE_UNSPECIFIED = MM.NoProductCode.UNSPECIFIED;

const MM_LABEL_NOTATION_BLANK = MM.LabelNotation["BLANK"];
const MM_LABEL_NOTATION_0 = MM.LabelNotation['0'];
const MM_LABEL_NOTATION_0_10 = MM.LabelNotation['0_10'];
const MM_LABEL_NOTATION_1 = MM.LabelNotation['1'];
const MM_LABEL_NOTATION_1_10 = MM.LabelNotation['1_10'];
const MM_LABEL_NOTATION_3 = MM.LabelNotation['3'];
const MM_LABEL_NOTATION_4 = MM.LabelNotation['4'];
const MM_LABEL_NOTATION_4_14 = MM.LabelNotation['4_14'];
const MM_LABEL_NOTATION_6 = MM.LabelNotation['6'];
const MM_LABEL_NOTATION_6_BLANK = MM.LabelNotation['6_BLANK'];
const MM_LABEL_NOTATION_6_BIG = MM.LabelNotation['6_BIG'];
const MM_LABEL_NOTATION_MM6_MMM = MM.LabelNotation['MM6_MMM'];
const MM_LABEL_NOTATION_MM6_MM = MM.LabelNotation['MM6_MM'];
const MM_LABEL_NOTATION_8 = MM.LabelNotation['8'];
const MM_LABEL_NOTATION_10 = MM.LabelNotation['10'];
const MM_LABEL_NOTATION_11 = MM.LabelNotation['11'];
const MM_LABEL_NOTATION_12 = MM.LabelNotation['12'];
const MM_LABEL_NOTATION_13 = MM.LabelNotation['13'];
const MM_LABEL_NOTATION_14 = MM.LabelNotation['14'];
const MM_LABEL_NOTATION_15 = MM.LabelNotation['15'];
const MM_LABEL_NOTATION_20 = MM.LabelNotation['20'];
const MM_LABEL_NOTATION_22 = MM.LabelNotation['22'];
const MM_LABEL_NOTATION_REP = MM.LabelNotation['REP'];
const MM_LABEL_NOTATION_HM = MM.LabelNotation['H_M'];
const MM_LABEL_NOTATION_TNF = MM.LabelNotation['TNF'];
const MM_LABEL_NOTATION_SUP = MM.LabelNotation['SUP'];
const MM_LABEL_NOTATION_UNSPECIFIED = MM.LabelNotation['UNSPECIFIED'];

const MM_MANUFACTURER_MII = MM.Manufacturer.MADE_IN_ITALY;
const MM_MANUFACTURER_MIF = MM.Manufacturer.MADE_IN_FRANCE;
const MM_MANUFACTURER_SI = MM.Manufacturer.STAFF_INTERNATIONAL;
const MM_MANUFACTURER_MAC = MM.Manufacturer.MACKINTOSH;
const MM_MANUFACTURER_MD_TOG = MM.Manufacturer.MISS_DEANNA_TOGETHER;
const MM_MANUFACTURER_MD_SEP = MM.Manufacturer.MISS_DEANNA_SEPARATED;
const MM_MANUFACTURER_MD = MM.Manufacturer.MISS_DEANNA;
const MM_MANUFACTURER_DS = MM.Manufacturer.DEANNA_SPA;
const MM_MANUFACTURER_UNSPECIFIED = MM.Manufacturer["UNSPECIFIED"];

const inputMM = [
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: "00324/982",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: "00324/982",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: "00324/992",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: "00905/011",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED }, // ss01
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: "00582/0012",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED }, // aw01
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: "01592/0042",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED }, // aw04
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: "02711/0062",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED }, // aw06
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: "01753/03/01/0071",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED }, // ss07
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: "00688/02/01/0101",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED }, // ss10? saw ss01
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: "10093/01/01/0102",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED }, // aw10? saw ss01
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: "02PR/2010/2253 - 2010 02",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED }, // aw10
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: "02CC/2012/60001 - 2012 02",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED }, // aw12
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: "02PR/2013/54 - 2013 02",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED }, // aw13
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: "01PR/2021/3473/1 - 2021 01",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED }, // ss21
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: "01PR/2021/3473/1 - 2021 01",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED }, // ss21
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: MM_CODE_BLANK,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: MM_CODE_BLANK,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_0_10, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_22, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_12, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_15, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: "00324/982",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1_10, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_4_14, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_6_BLANK, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_6, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_MM6_MMM, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_MM6_MM, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_6_BIG, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_22, productCode: "P01PR 2018 1299/3",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_22, productCode: "P02PR 21 774/1",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_22, productCode: "02PR 2017 774/1",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_22, productCode: "P02PR 2017 774/1",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_22, productCode: "02PR 2019 774/1",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_22, productCode: "P02PR 2019 774/1",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_6, productCode: "P02PR 2019 774/1",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_6, productCode: "02PR 2021 774/1",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_20, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_REP, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_HM, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_TNF, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_SUP, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: MM_CODE_UNSPECIFIED,
            manufacturer: MM_MANUFACTURER_SI },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: MM_CODE_UNSPECIFIED,
            manufacturer: MM_MANUFACTURER_MAC },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: "01SP/2022/55348/1 - 2022 1", // SS22
            manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: "02PR 22 5107/1 2022", // AW22
            manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: MM_CODE_UNSPECIFIED,
            manufacturer: MM_MANUFACTURER_MIF },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_0, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_MIF },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_0, productCode: MM_CODE_BLANK,
        manufacturer: MM_MANUFACTURER_MIF },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: MM_CODE_BLANK,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: "02711/0062",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_SI },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_MII },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_10, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_MII },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: "01PR/2022/2901/1",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_BLANK, productCode: MM_CODE_UNSPECIFIED,
        manufacturer: MM_MANUFACTURER_MD_SEP },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_10, productCode: "01PR/2017/4891 - 2017 01",
        manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: MM_CODE_UNSPECIFIED,
            manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_6_BIG, productCode: MM_CODE_UNSPECIFIED,
            manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_MM6_MMM, productCode: MM_CODE_UNSPECIFIED,
            manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_MM6_MM, productCode: MM_CODE_UNSPECIFIED,
            manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: MM_LABEL_NOTATION_1, productCode: "01PR/2022/2901/1",
            manufacturer: MM_MANUFACTURER_UNSPECIFIED },
    { label: MM.Label, labelNotation: "1", productCode: MM_CODE_UNREADABLE,
            manufacturer: MM_MANUFACTURER_MAC },
];

let input = inputIM;

let count = 1;
for (let test of input) {
    console.log(`----------------\nTEST #${count}\n----------------\n`
                + identify(test));
    ++count;
}

let readme = false;

if (readme) {
    console.log(identify({
        label: CDG.Label,
        productCode: "GJ-10009S",
        yearPrint: "1994"
    }));
    console.log(JSON.stringify(extract({
        label: CDG.Label,
        productCode: "GJ-10009S",
        yearPrint: "1994"
    })));
    console.log(identify({
        label: CDG.Label,
        productCode: "GJ-10009S",
        yearPrint: CDG.NoYearPrint.UNREADABLE
    }));
    console.log(identify({
        label: IM.Label,
        productCode: "IM02-FD012",
        logoStyle: IM_LOGO_IM_BLACK_ON_WHITE,
        manufacturer: IM_MANUFACTURER_IM_INC,
        sizing: IM_SIZING_ALPHABETICAL,
        typeface: IM_TYPEFACE_SLAB_SERIF }))
    console.log(identify({
        label: YY.Label,
        logoStyle: YY.LogoStyle.YY[3],
        productCode: "FY-C10-104",
        sizing: YY.Sizing.ALPHABETICAL,
        typeface: YY.Typeface.PROPORTIONAL,
        language: YY.Language.FR_EN_JP,
        laundryPosition: YY.LaundryPosition.BOTTOM,
        manufacturer: YY.Manufacturer.UNSPECIFIED,
    }));
}
